spring:
  output:
    ansi:
      enabled: ALWAYS

#feign:
#  client:
#    config:
#      aery-feign:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full
#        retryer:
#        requestInterceptors[0]:
#        requestInterceptors[1]:
#        encoder:
#        decoder:
#        contract:

